apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-disk-1
  labels:
    name: es-disk-1
spec:
  capacity:
    storage: 2048Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-08aa24cab6dec8ebc"
    fsType: "ext4"
